### ISSUE TITLE
Minha experiência com Solr

### ISSUE THREAD

**Issue by renanpalmeira** [ajunior/solr#1]
Com certeza, uma ferramenta muito boa, porém tive experiências muito ruins, como:

* Na questão de configuração, pouco coisa eu achei sobre isso, quando achava versão antiga;
* O schema.xml, um terror pra mexer nele;
* Migração entre um versão e outra, em outros players do mercado que usam o Lucene, é bem simples migrar de uma versão pra outra, as vezes só colocando os arquivos do Lucene, caso isso não seja possível, normalmente tem uma ferramenta que funciona para fazer tal coisa, até hoje essa é a segunda pior parte de trabalhar com solr, a primeira é configuração mesmo.
* Sinto falta de guias como esse ou algo tipo "best practices";
* Documentação é mais ou menos, até hoje, eu passei pelo solr 4 até 5, hoje testando o 6, nunca me ajudou muito, normalmente eu acabo indo no github, lendo algum blog post para conseguir fazer a alteração em questão.
     * Autenticação é um exemplo disso, tudo que fala na documentação sobre autenticação no Solr, eu não consegui fazer, acabei tento que ir em blog post ou perguntar em user group's de Solr (que infelizmente são bem poucos).

Passando apenas um relato mesmo, é uma ótima ferramenta, os livros também ajudam bastante em algumas coisas, apesar que normalmente o livro não esta na ultima versão. 

Uma ótima ideia desse manual, espero que ele continue e possivelmente vou estar fazendo alguns pull request's :smile: .

**Comment by ajunior** [comment]
@RenanPalmeira Interessante seu relato. Eu estou passando por essa dificuldade. Estou implementando o Solr 6.3.0 na empresa pública onde estou estagiando. Resolvi escrever tudo que eu fosse testando e agora estou organizando nesse manual para ajudar outros interessados. Fico agradecido pelo seu contato e pela sua ajuda, espero mesmo ver a comunidade contribuindo.

Forte abraço.

**Comment by renanpalmeira** [comment]
@ajunior Uma ótima ideia mesmo, eu estou acompanhando o repo, muito boa a ideia mesmo. 

Segue um link, que talvez ajude você em algum momento trabalhando com Solr, se a 6 meses atrás eu tivesse ele, não teria alguns problemas que eu citei ai em cima. 

http://dlightdaily.com/2016/11/30/configure-apache-lucene-solr-cloud-external-zookeeper/

Solr é uma ótima ferramenta, porém o marketing e o suporte que a Elastic da para o elasticsearch tem sido tentador para trocar o Solr.
